### ISSUE TITLE
Masks wont save

### ISSUE THREAD

**Issue by josephldobson** [vye16/shape-of-motion#11]
When running python mask_app.py --root_dir on custom data unable to save masks:

Traceback (most recent call last):
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
    result = await self.call_function(
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/joe/miniconda3/envs/som/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
    response = f(*args, **kwargs)
  File "/home/joe/repos/shape-of-motion/preproc/mask_app.py", line 162, in run_tracker
    self.lazy_init_tracker()
  File "/home/joe/repos/shape-of-motion/preproc/mask_app.py", line 48, in lazy_init_tracker
    self.tracker = init_tracker(self.checkpoint_dir, self.device)
  File "/home/joe/repos/shape-of-motion/preproc/mask_utils.py", line 25, in init_tracker
    raise ValueError(f"No XMem checkpoints found in {checkpoint_dir}")
ValueError: No XMem checkpoints found in checkpoints

**Comment by adsjkgh** [comment]
You should keep the "XMem-s012.pth" under the /shape-of-motion/preproc/checkpoints folder. Like this
![271698292c34c58b3b10ea48d1015a0](https://github.com/user-attachments/assets/3d712cfb-80a9-41d7-b21c-7447449a2a26)

**Comment by OliEfr** [comment]
Had the same issue. By default it gets downloaded to `saves`. Manually moving it fixed it for me.
