### ISSUE TITLE
npy does not exist. Path Issue?

### ISSUE THREAD

**Issue by aris-t** [vye16/shape-of-motion#12]
python run_training.py --work-dir ./outdir data:custom --data.seq-name untitled --data.root-dir ./preproc/indir/

Traceback (most recent call last):
  File "/home/ubuser/Desktop/shape-of-motion/run_training.py", line 254, in <module>
    main(tyro.cli(TrainConfig))
  File "/home/aris/Desktop/shape-of-motion/run_training.py", line 80, in main
    get_train_val_datasets(cfg.data, load_val=True)
  File "/home/aris/Desktop/shape-of-motion/flow3d/data/__init__.py", line 36, in get_train_val_datasets
    train_dataset = CasualDataset(**asdict(data_cfg))
  File "/home/aris/Desktop/shape-of-motion/flow3d/data/casual_dataset.py", line 136, in __init__
    w2cs, Ks, tstamps = load_cameras(
  File "/home/aris/Desktop/shape-of-motion/flow3d/data/casual_dataset.py", line 456, in load_cameras
    assert os.path.exists(path), f"Camera file {path} does not exist."
AssertionError: Camera file ./preproc/indir//droid_recon/untitled.npy does not exist.

I think it is looking for:
/home/ubuser/Desktop/shape-of-motion/preproc/indir/bootstapir/untitled

This directory has:
├── 00001_00001.npy
├── 00001_00002.npy
├── 00001_00003.npy
├── 00001_00004.npy
...

Is it possible the file packaging has changed?

**Comment by qianqianwang68** [comment]
Sorry I'm confused, reading the assertion error, it seems that it's the camera file ./preproc/indir//droid_recon/untitled.npy  which does not exist?
