### ISSUE TITLE
RuntimeError: quantile() input tensor must be non-empty

### ISSUE THREAD

**Issue by adsjkgh** [vye16/shape-of-motion#13]
(som) ygz@Ubuntu:/shape-of-motion$ python run_training.py --work-dir ./data/som2/ data:custom --data.seq-name cam01 --data.root-dir ./data/cook_spinach/
2024-07-24 11:23:13.397 | DEBUG    | flow3d.data.casual_dataset:load_cameras:458 - recon.keys()=dict_keys(['tstamps', 'images', 'points', 'masks', 'map_c2w', 'traj_c2w', 'intrinsics', 'img_shape'])
./shape-of-motion/flow3d/data/casual_dataset.py:490: UserWarning: Using torch.cross without specifying the dim arg is deprecated.
Please either pass the dim explicitly or simply use torch.linalg.cross.
The default value of dim will change to agree with that of linalg.cross in a future release. (Triggered internally at ../aten/src/ATen/native/Cross.cpp:63.)
  F.normalize(original_up.cross(target_up), dim=-1)
2024-07-24 11:23:14.211 | INFO     | flow3d.data.casual_dataset:__init__:170 - scene norm self.scale=1.056371808052063, transform=tensor([[ 1.0000e+00, -6.0561e-05,  6.0569e-05, -6.6507e-01],
        [-6.0561e-05,  1.2583e-04,  1.0000e+00, -1.7826e+00],
        [-6.0569e-05, -1.0000e+00,  1.2582e-04,  6.1083e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  1.0000e+00]])
2024-07-24 11:23:14.212 | INFO     | __main__:main:82 - Training dataset has 300 frames
Traceback (most recent call last):
  File "./shape-of-motion/run_training.py", line 254, in <module>
    main(tyro.cli(TrainConfig))
  File "./shape-of-motion/run_training.py", line 93, in main
    initialize_and_checkpoint_model(
  File "./shape-of-motion/run_training.py", line 179, in initialize_and_checkpoint_model
    fg_params, motion_bases, bg_params, tracks_3d = init_model_from_tracks(
  File "./shape-of-motion/run_training.py", line 209, in init_model_from_tracks
    tracks_3d = TrackObservations(*train_dataset.get_tracks_3d(num_fg))
  File "./shape-of-motion/flow3d/data/casual_dataset.py", line 288, in get_tracks_3d
    tracks_tuple = get_tracks_3d_for_query_frame(
  File "./shape-of-motion/flow3d/data/utils.py", line 150, in get_tracks_3d_for_query_frame
    visible_counts.float().quantile(0.1).item(),
RuntimeError: quantile() input tensor must be non-empty

What's the problem? Thank you very much!

**Comment by vye16** [comment]
thank you for pointing this out. it looks like `visible_counts` is empty. could you check if the `tracks_2d` input to that function actually has any tracks?

**Comment by heimrabe** [comment]
Hi, I am facing the same issue when fitting on custom data. tracks_2d is indeed empty when facing this RuntimeError

**Comment by Daydreamer-f** [comment]
I met the same problem. I have a total of 347 frames, and I met this issue at the 346th frame. The output of `torchs_2d` is empty. I printed the values from the `load_target_tracks` function, but there didn't seem to be any anomalies at the 346th frame `(path` is not empty, `all_tracks` is not empty and has a dimension of 347). What could be the reason for this? Has anyone solved this problem while training on custom dataset?

**Comment by xyzalanix** [comment]
Hey, I was also facing this issue with a dataset of 253 frames. I found out it was running into this issue at `q_idx `251, which would be an incomplete tensor, followed by an empty one:

```
frame 0 torch.Size([159, 253, 4]) 
...
frame 250 torch.Size([159, 253, 4])
frame 251 torch.Size([91, 253, 4])        !! incomplete ?
frame 252 torch.Size([0, 253, 4])          !! (empty)
```

I'm assuming it's something to do with how compute_tracks unpacks and segments data ? Maybe even something to do with odd / pair number of frames ?

Anyway, I was able to move on to training by deleting the last frames of my dataset, now 250 frames long. Curious to find out what's behind this

**Comment by emjay73** [comment]
I encountered the same error. How can I handle this?

**Comment by rhodriguerrier** [comment]
@vye16 I also get this error whenever one of my moving object masks leaves the screen. Does the method only work for objects that stay within the field of view? Or is there a way to fix this issue? Thanks
