### ISSUE TITLE
Issues with save masks

### ISSUE THREAD

**Issue by DWJ111** [vye16/shape-of-motion#42]
Hi, when I tried preprocessing, I encountered this error: "Current selection" and "Masked video" don't have pictures.
![Uploading QQ图片20240818194033.png…]()

**Comment by qianqianwang68** [comment]
Do you see any errors in the terminal?

**Comment by liyaowei-stu** [comment]
same problem.

**Comment by xizaoqu** [comment]
Hi, it is the gradio problem. The newest version has bugs in Image.select(). Try to downgrade it into like 4.13.0.

**Comment by ricshaw** [comment]
I downgraded Gradio and now I can see the selection, but the tracking doesn't work. I just get an error.

![image](https://github.com/user-attachments/assets/a3292240-29d2-431b-a62d-1df011b2ac3f)


Traceback (most recent call last):
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/gradio/queueing.py", line 489, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/gradio/route_utils.py", line 232, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/gradio/blocks.py", line 1561, in process_api
    result = await self.call_function(
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/gradio/blocks.py", line 1179, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/gradio/utils.py", line 678, in wrapper
    response = f(*args, **kwargs)
  File "/home/ma-user/work/richards/shape-of-motion/preproc/mask_app.py", line 162, in run_tracker
    self.lazy_init_tracker()
  File "/home/ma-user/work/richards/shape-of-motion/preproc/mask_app.py", line 48, in lazy_init_tracker
    self.tracker = init_tracker(self.checkpoint_dir, self.device)
  File "/home/ma-user/work/richards/shape-of-motion/preproc/mask_utils.py", line 27, in init_tracker
    return BaseTracker(checkpoints[-1], device)
  File "/home/ma-user/work/richards/shape-of-motion/preproc/tracker/base_tracker.py", line 33, in __init__
    network = XMem(config, xmem_checkpoint).to(device).eval()
  File "/home/ma-user/work/richards/shape-of-motion/preproc/tracker/model/network.py", line 23, in __init__
    model_weights = self.init_hyperparameters(config, model_path, map_location)
  File "/home/ma-user/work/richards/shape-of-motion/preproc/tracker/model/network.py", line 176, in init_hyperparameters
    model_weights = torch.load(model_path, map_location="cpu")
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/torch/serialization.py", line 1005, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/ma-user/miniconda3/envs/gaussian_splatting/lib/python3.10/site-packages/torch/serialization.py", line 457, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central director

**Comment by ricshaw** [comment]
Nevermind, it seems the XMem checkpoint didn't download correctly or was corrupted

**Comment by rhodriguerrier** [comment]
Hi @xizaoqu, I am also having this issue. When I downgrade to 4.13.0, I can't load the image directory any more. I instead get an error saying:
`ERROR:    Exception in ASGI application` and `AttributeError: __pydantic_core_schema__`
Do you know the fix for this? Thanks

**Comment by rhodriguerrier** [comment]
@xizaoqu I downgraded to 4.40.0 and it has solved both errors for me so don't worry. Cheers

**Comment by donghaoye** [comment]
@rhodriguerrier Could you show your pip list packages? 
When I downgraded to 4.40.0 and ran again, it still didn't show anything in the current selection.

**Comment by shashwatsuri** [comment]
I found 4.40.0 for me was leading to other issues like [https://github.com/gradio-app/gradio/issues/9278#issue-2509191121](url). To solve that, also downgrade fastapi to 0.112.2 to fix the issue.

**Comment by lihao1477024473** [comment]
Hi @xizaoqu, I am also having this issue. I downgraded to 4.40.0.I found 4.40.0 for me was leading to other issues like：
 File "/root/miniconda3/lib/python3.12/site-packages/pydantic/_internal/_generate_schema.py", line 513, in _unknown_type_schema
    raise PydanticSchemaGenerationError(
pydantic.errors.PydanticSchemaGenerationError: Unable to generate pydantic-core schema for <class 'starlette.requests.Request'>. Set `arbitrary_types_allowed=True` in the model_config to ignore this error or implement `__get_pydantic_core_schema__` on your type to fully support it.

If you got this error by calling handler(<some type>) within `__get_pydantic_core_schema__` then you likely need to call `handler.generate_schema(<some type>)` since we do not call `__get_pydantic_core_schema__` on `<some type>` otherwise to avoid infinite recursion.

For further information visit https://errors.pydantic.dev/2.10/u/schema-for-unknown-type
