### ISSUE TITLE
Error using Tyro

### ISSUE THREAD

**Issue by Daeen** [vye16/shape-of-motion#63]
(som) root@userver71:/home/shape-of-motion# python run_training.py --work-dir /home/shape-of-motion/output --port 8008 data:iphone --data.data-dir /data/datasets/iphone/backpack
Traceback (most recent call last):
  File "/home/shape-of-motion/run_training.py", line 254, in <module>
    main(tyro.cli(TrainConfig))
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_cli.py", line 166, in cli
    output = _cli_impl(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_cli.py", line 380, in _cli_impl
    parser_spec = _parsers.ParserSpecification.from_callable_or_type(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 124, in from_callable_or_type
    field_out = handle_field(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 359, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 569, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 124, in from_callable_or_type
    field_out = handle_field(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 359, in handle_field
    subparsers_attempt = SubparsersSpecification.from_field(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 569, in from_field
    subparser = ParserSpecification.from_callable_or_type(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 124, in from_callable_or_type
    field_out = handle_field(
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_parsers.py", line 404, in handle_field
    return _arguments.ArgumentDefinition(
  File "<string>", line 7, in __init__
  File "/root/anaconda3/envs/som/lib/python3.10/site-packages/tyro/_arguments.py", line 118, in __post_init__
    raise UnsupportedTypeAnnotationError(
tyro.constructors._primitive_spec.UnsupportedTypeAnnotationError: Field scale is missing a default value!
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

I am getting this error, despite carefully following the instructions. There seems to be very little documentation regarding this similar type error on the internet.

**Comment by brentyi** [comment]
@Daeen could you check if `pip install --upgrade tyro` fixes this for you?

**Comment by Daeen** [comment]
Thanks! It works now.
