### ISSUE TITLE
Some small bugs when running som

### ISSUE THREAD

**Issue by guanjunwu** [vye16/shape-of-motion#9]
Hi, thanks for your great work!
I have two small bugs:
1. when input images are RGBA images, the preprocessing progress will shut.
2. unidepth seems already updated, maybe can use unidepth_v2? e.g.:
`    model = UniDepthV2.from_pretrained("lpiccinelli/unidepth-v2-vitl14")`
in the file `preproc/compute_metric_depth`
(when running V1, bug reported:
```
Traceback (most recent call last):
  File "/data/guanjunwu/disk2/code/shape-of-motion/preproc/compute_metric_depth.py", line 99, in <module>
    tyro.cli(run_model_inference)
  File "/data/guanjunwu/disk2/miniconda3/envs/som/lib/python3.10/site-packages/tyro/_cli.py", line 217, in cli
    return run_with_args_from_cli()
  File "/data/guanjunwu/disk2/code/shape-of-motion/preproc/compute_metric_depth.py", line 25, in run_model_inference
    model = UniDepthV1.from_pretrained("lpiccinelli/unidepth-v1-vitl14")
  File "/data/guanjunwu/disk2/miniconda3/envs/som/lib/python3.10/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "/data/guanjunwu/disk2/miniconda3/envs/som/lib/python3.10/site-packages/huggingface_hub/hub_mixin.py", line 569, in from_pretrained
    instance = cls._from_pretrained(
  File "/data/guanjunwu/disk2/miniconda3/envs/som/lib/python3.10/site-packages/huggingface_hub/hub_mixin.py", line 789, in _from_pretrained
    model = cls(**model_kwargs)
TypeError: UniDepthV1.__init__() missing 1 required positional argument: 'config'
```

Best

**Comment by vye16** [comment]
Hi, thank you for the comments!
1. does #16 help with this?
2. I can't seem to reproduce this bug -- I'm on Unidepth's commit `bebc4b2`. Could you provide more details about this failure and your env?

**Comment by lxin98** [comment]
601/5000
I also encountered TypeError: UniDepthV1.__init__() missing 1 required positional argument: 'config'
Problems, I is to perform the python launch_metric_depth py - img - dirs/home/lanxin/Desktop/data/data_root/images / * * - gpus 0 command when encountered. I run mask_app.py and generate the mask file for images. Under /data_root/images/1629112487-1-100111/images and /data_root/masks/1629112487-1-100111 respectively, I want to know CUDA_VISIBLE_DEVICES=0 python compute_metric_depth.py --img-dir data/data_root/images/1629112487-1-100111 --depth-dir  data_root/unidepth_disp/1629112487-1-100111 --intrins-file  data_root/unidepth_intrins/1629112487-1-100111.json, is 1629112487-1-100111.json an input file and how should I provide this file @vye16

**Comment by guanjunwu** [comment]
Hi, I'm on the latest commit.
And I only follow your setups to create my env :)
python 3.10.14 torch 2.2.0+cu118
